### ISSUE TITLE
Implement Organization model

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/EventTrakka-Backend#11]
The Organization model is a representation of the different tech communities that can be created on eventtrakka. The current Organization model is commented out located in EventTrakka-Backend/app/models/organizations.py has a mismatch from the current data the front end has. reference the frontend at https://event-trakka.vercel.app/view to decide what additional fields should be added or removed from the model

**Comment by festuscharles-n** [comment]
You want me to do this right?

**Comment by gray-adeyi** [comment]
Attempt #19 instead. It's an easy fix
