### ISSUE TITLE
Implement Attendee Model

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/EventTrakka-Backend#12]
The Attendee model is a representation of the different users who rsvp upcoming tech events on eventtrakka. The current Attendee model is commented out located in EventTrakka-Backend/app/models/attendees.py has a mismatch from the current data the front end has. reference the frontend at https://event-trakka.vercel.app/view to decide what additional fields should be added or removed from the model

**Comment by festuscharles-n** [comment]
Assign this to me sir .🫣
