### ISSUE TITLE
Send email to newly signed up user to verify email address

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/EventTrakka-Backend#5]
Currently, the `/api/v1/auth/signup` bypasses the email verification flow by setting `is_email_verified=True`, it should be `False` and before returning a response to the client, an email should be sent to the newly signed up user as a background task after which the user clicks the link present in the email to verify the email

**Comment by festuscharles-n** [comment]
Why are we using a verification link instead of using OTP...?

**Comment by festuscharles-n** [comment]
which one, Link or OTP?
i know the flow, i just want to be sure of which one we'll be using

**Comment by festuscharles-n** [comment]
assign this to me

**Comment by gray-adeyi** [comment]
Assigned
