### ISSUE TITLE
Implement Forgot password

### ISSUE THREAD

**Issue by gray-adeyi** [OSCA-Ado-Ekiti/EventTrakka-Backend#8]
This is the endpoint that starts the password reset flow, it accepts the user's email address as the payload data, verifies the user exist then sends them an email to reset their password

**Comment by VictorAO-django** [comment]
I'll like to work on this.. kindly assign me

**Comment by gray-adeyi** [comment]
Hi @VictorAO-django I see you've requested to work on multiple issues. I can only assign one to you at a time. Please reply in any of the issues you're most interested in after you've correctly set up the project locally. see the `CONTRIBUTING.md` for more on how to do that

**Comment by VictorAO-django** [comment]
@OSCA-Ado-Ekiti I'll start with this issue
